### ISSUE TITLE
I'm leaving Github

### ISSUE THREAD

**Issue by y-p** [pandas-docs/pandas-docs-travis#2]
hello @pandas-docs/powners, 

I'll be deleting my Github account momentarily. A bunch of you are owners now, I see, so this shouldn't disrupt anything. You should probably replace it with something under pandas-dev.  
 
I don't recognize what FOSS has become and I haven't for quite a while. Now that Microsoft has acquired Github and no one is even pretending any more, it seems like the right time to finally pull this particular trigger.

Live a good life. Make good choices.

y-p

**Comment by TomAugspurger** [comment]
Indeed, thank you y-p. You reviewed my first PR to pandas and walked me
through all the git commands to fix my branch which I managed to mess up.

**Comment by jreback** [comment]
best of luck @y-p

**Comment by cpcloud** [comment]
Thanks for all you did for pandas y-p. In my book, you easily win the award for "best code reviewer". You were always patient and helpful when I screwed something up in a PR. The open source world will miss you. Best of luck.
